server:
  port: 7001 #eureka  服务端口
eureka:
  instance:
    hostname: eureka-server7001 #eureka  hostname
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上获取服务的注册信息
    service-url:
      defaultZone: http://localhost:7002/eureka/